# training 

epochs: 1000
csv_file: "/home/valentin/Desktop/personal_work/memento_interview/TST/A-Transformer-based-Framework-for-Multivariate-Time-Series-Representation-Learning/nasdaq100_padding.csv"
target: "NDX"
batch_size: 128

# model 
timesteps: 25
d_dim: 128
dim_ffw: 256
num_layers: 3
num_heads: 8
num_exogenous: 81
dropout: 0.2


lr: 0.0001
train_split: 0.75
val_split: 0.15

# regression
out_dim: 1