# training 

epochs: 250
csv_file: "/home/valentin/Desktop/personal_work/memento_interview/TST/A-Transformer-based-Framework-for-Multivariate-Time-Series-Representation-Learning/nasdaq100_padding.csv"
target: "NDX"
batch_size: 64

# model 
timesteps: 5
d_dim: 64
dim_ffw: 64
num_layers: 2
num_heads: 8
num_exogenous: 81
dropout: 0.2

lr: 0.00005
train_split: 0.75
val_split: 0.15

# regression
out_dim: 1