# training 

epochs: 1000
csv_file: "/home/valentin/Desktop/interview_memento_ai/TFMTSRL/TFMTSRL/nasdaq100_padding.csv"
target: "NDX"
batch_size: 128

# model 
timesteps: 10
d_dim: 64
dim_ffw: 64
num_layers: 3
num_heads: 8
num_exogenous: 81
dropout: 0.1

lr: 0.0001
train_split: 0.75
val_split: 0.15

# reconstruction
out_dim: 81


# mask
mask_r: 0.3
lm: 3